### ISSUE TITLE
Installation of the app

### ISSUE THREAD

**Issue by 7ory** [mchudy/InstantDelivery#1]
I downloaded the zip of the project and when I opened it I installed all dependencies from the NuGet package manager but I still get an error saying I'm missing 20 components.
![image](https://user-images.githubusercontent.com/50345453/103712359-4b451380-4fc2-11eb-998b-4e6f641332ca.png)

**Comment by duszakpawel** [comment]
I don't remember having this issue while working on this project. I'm not sure what causes this issue, maybe it's dependent on the SDK version. Try updating the Fody nuget version to 1.29.4; after that I was able to compile the solution under vs2019.

**Comment by 7ory** [comment]
How do I go on doing that? as in what do I type in the NeGet 
package manager Console?

**Comment by duszakpawel** [comment]
You can use the following command:
Update-Package Fody -Version 1.29.4

**Comment by 7ory** [comment]
![image](https://user-images.githubusercontent.com/50345453/104140302-79a76200-53b9-11eb-91dc-be33366c0b69.png)
After I updated the SDK I got this now

**Comment by duszakpawel** [comment]
make sure you don't override the FodyWeavers.xml during the installation, there is a prompt in command line, you have to decline it.

**Comment by 7ory** [comment]
Oh yeah i overrode it
